.PHONY: server client clean

server:
	@echo "Starting server..."
	@go run ./cmd/server/srunner.go

client:
	@echo "Starting client..."
	@go run ./cmd/client/crunner.go

clean:
	@echo "Cleaning build cache..."
	@go clean

